# first stage
FROM nvidia/cuda:11.1-base-ubuntu18.04 as builder
WORKDIR /app
RUN apt-get update && apt-get install -y curl wget gcc build-essential
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda
RUN /opt/conda/bin/conda create -y -n pwgan python=3.8.5
ENV PATH=/opt/conda/envs/pwgan/bin:$PATH
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY requirements_gpu.txt /app
RUN pip install --no-cache-dir -r requirements_gpu.txt
RUN pip uninstall -y pip

# second stage
FROM nvidia/cuda:11.1-base-ubuntu18.04 as runner
WORKDIR /app
RUN apt-get update && apt-get install -y libsndfile1
COPY --from=builder /opt/conda/envs/pwgan/bin /opt/conda/envs/pwgan/bin
COPY --from=builder /opt/conda/envs/pwgan/lib /opt/conda/envs/pwgan/lib
ENV PATH=/opt/conda/envs/pwgan/bin:$PATH
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

## final image
from runner
COPY ./run.py /app
COPY ./service /app/service
CMD [ "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "8000"]