version: '3.7'

services:
  pwgan-serving:
    image: airenas/pwgan-pytorch-serving-gpu:${SERVICE_VERSION}
    ports:
      - "${SERVICE_PORT}:8000"
    environment:
      CONFIG_FILE: /config/voices.yaml
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all
    # restart: unless-stopped
    volumes:
      - ${MODELS_PATH}:/models:ro
      - ./voices.yaml:/config/voices.yaml:ro
    runtime: nvidia
